//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpyClientLibrary.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientRequest", Namespace="http://schemas.datacontract.org/2004/07/SpyWcfService.Messages")]
    [System.SerializableAttribute()]
    public partial class ClientRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] _dataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime _scrrenDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _scrrenNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] _data {
            get {
                return this._dataField;
            }
            set {
                if ((object.ReferenceEquals(this._dataField, value) != true)) {
                    this._dataField = value;
                    this.RaisePropertyChanged("_data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime _scrrenDate {
            get {
                return this._scrrenDateField;
            }
            set {
                if ((this._scrrenDateField.Equals(value) != true)) {
                    this._scrrenDateField = value;
                    this.RaisePropertyChanged("_scrrenDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _scrrenName {
            get {
                return this._scrrenNameField;
            }
            set {
                if ((object.ReferenceEquals(this._scrrenNameField, value) != true)) {
                    this._scrrenNameField = value;
                    this.RaisePropertyChanged("_scrrenName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _username {
            get {
                return this._usernameField;
            }
            set {
                if ((object.ReferenceEquals(this._usernameField, value) != true)) {
                    this._usernameField = value;
                    this.RaisePropertyChanged("_username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IClientService")]
    public interface IClientService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/SaveScreenShotToDB", ReplyAction="http://tempuri.org/IClientService/SaveScreenShotToDBResponse")]
        bool SaveScreenShotToDB(SpyClientLibrary.ServiceReference.ClientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/SaveScreenShotToDB", ReplyAction="http://tempuri.org/IClientService/SaveScreenShotToDBResponse")]
        System.Threading.Tasks.Task<bool> SaveScreenShotToDBAsync(SpyClientLibrary.ServiceReference.ClientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/GetScreenFromDB", ReplyAction="http://tempuri.org/IClientService/GetScreenFromDBResponse")]
        byte[] GetScreenFromDB();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/GetScreenFromDB", ReplyAction="http://tempuri.org/IClientService/GetScreenFromDBResponse")]
        System.Threading.Tasks.Task<byte[]> GetScreenFromDBAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClientServiceChannel : SpyClientLibrary.ServiceReference.IClientService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientServiceClient : System.ServiceModel.ClientBase<SpyClientLibrary.ServiceReference.IClientService>, SpyClientLibrary.ServiceReference.IClientService {
        
        public ClientServiceClient() {
        }
        
        public ClientServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SaveScreenShotToDB(SpyClientLibrary.ServiceReference.ClientRequest request) {
            return base.Channel.SaveScreenShotToDB(request);
        }
        
        public System.Threading.Tasks.Task<bool> SaveScreenShotToDBAsync(SpyClientLibrary.ServiceReference.ClientRequest request) {
            return base.Channel.SaveScreenShotToDBAsync(request);
        }
        
        public byte[] GetScreenFromDB() {
            return base.Channel.GetScreenFromDB();
        }
        
        public System.Threading.Tasks.Task<byte[]> GetScreenFromDBAsync() {
            return base.Channel.GetScreenFromDBAsync();
        }
    }
}
