//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpyClientConsole.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IClientService")]
    public interface IClientService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/SaveScreenShotToDB", ReplyAction="http://tempuri.org/IClientService/SaveScreenShotToDBResponse")]
        bool SaveScreenShotToDB(SpyClientLibrary.ServiceReference.ClientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/SaveScreenShotToDB", ReplyAction="http://tempuri.org/IClientService/SaveScreenShotToDBResponse")]
        System.Threading.Tasks.Task<bool> SaveScreenShotToDBAsync(SpyClientLibrary.ServiceReference.ClientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/GetScreenFromDB", ReplyAction="http://tempuri.org/IClientService/GetScreenFromDBResponse")]
        byte[] GetScreenFromDB();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/GetScreenFromDB", ReplyAction="http://tempuri.org/IClientService/GetScreenFromDBResponse")]
        System.Threading.Tasks.Task<byte[]> GetScreenFromDBAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/GetPagesGroupFromDB", ReplyAction="http://tempuri.org/IClientService/GetPagesGroupFromDBResponse")]
        SpyClientLibrary.ServiceReference.AcceptablePagesGroup[] GetPagesGroupFromDB();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/GetPagesGroupFromDB", ReplyAction="http://tempuri.org/IClientService/GetPagesGroupFromDBResponse")]
        System.Threading.Tasks.Task<SpyClientLibrary.ServiceReference.AcceptablePagesGroup[]> GetPagesGroupFromDBAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/GetAcceptablePageFromDB", ReplyAction="http://tempuri.org/IClientService/GetAcceptablePageFromDBResponse")]
        SpyClientLibrary.ServiceReference.AcceptablePage[] GetAcceptablePageFromDB();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/GetAcceptablePageFromDB", ReplyAction="http://tempuri.org/IClientService/GetAcceptablePageFromDBResponse")]
        System.Threading.Tasks.Task<SpyClientLibrary.ServiceReference.AcceptablePage[]> GetAcceptablePageFromDBAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/GetAcceptablePageForGroupFromDB", ReplyAction="http://tempuri.org/IClientService/GetAcceptablePageForGroupFromDBResponse")]
        SpyClientLibrary.ServiceReference.AcceptablePage[] GetAcceptablePageForGroupFromDB(int GroupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientService/GetAcceptablePageForGroupFromDB", ReplyAction="http://tempuri.org/IClientService/GetAcceptablePageForGroupFromDBResponse")]
        System.Threading.Tasks.Task<SpyClientLibrary.ServiceReference.AcceptablePage[]> GetAcceptablePageForGroupFromDBAsync(int GroupId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClientServiceChannel : SpyClientConsole.ServiceReference.IClientService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientServiceClient : System.ServiceModel.ClientBase<SpyClientConsole.ServiceReference.IClientService>, SpyClientConsole.ServiceReference.IClientService {
        
        public ClientServiceClient() {
        }
        
        public ClientServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SaveScreenShotToDB(SpyClientLibrary.ServiceReference.ClientRequest request) {
            return base.Channel.SaveScreenShotToDB(request);
        }
        
        public System.Threading.Tasks.Task<bool> SaveScreenShotToDBAsync(SpyClientLibrary.ServiceReference.ClientRequest request) {
            return base.Channel.SaveScreenShotToDBAsync(request);
        }
        
        public byte[] GetScreenFromDB() {
            return base.Channel.GetScreenFromDB();
        }
        
        public System.Threading.Tasks.Task<byte[]> GetScreenFromDBAsync() {
            return base.Channel.GetScreenFromDBAsync();
        }
        
        public SpyClientLibrary.ServiceReference.AcceptablePagesGroup[] GetPagesGroupFromDB() {
            return base.Channel.GetPagesGroupFromDB();
        }
        
        public System.Threading.Tasks.Task<SpyClientLibrary.ServiceReference.AcceptablePagesGroup[]> GetPagesGroupFromDBAsync() {
            return base.Channel.GetPagesGroupFromDBAsync();
        }
        
        public SpyClientLibrary.ServiceReference.AcceptablePage[] GetAcceptablePageFromDB() {
            return base.Channel.GetAcceptablePageFromDB();
        }
        
        public System.Threading.Tasks.Task<SpyClientLibrary.ServiceReference.AcceptablePage[]> GetAcceptablePageFromDBAsync() {
            return base.Channel.GetAcceptablePageFromDBAsync();
        }
        
        public SpyClientLibrary.ServiceReference.AcceptablePage[] GetAcceptablePageForGroupFromDB(int GroupId) {
            return base.Channel.GetAcceptablePageForGroupFromDB(GroupId);
        }
        
        public System.Threading.Tasks.Task<SpyClientLibrary.ServiceReference.AcceptablePage[]> GetAcceptablePageForGroupFromDBAsync(int GroupId) {
            return base.Channel.GetAcceptablePageForGroupFromDBAsync(GroupId);
        }
    }
}
