//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpyWcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamSession
    {
        public int ExamSessionId { get; set; }
        public string Name { get; set; }
        public Nullable<int> AcceptablePagesGroupId { get; set; }
        public Nullable<int> WorkStationsGroupId { get; set; }
    
        public virtual AcceptablePagesGroup AcceptablePagesGroup { get; set; }
        public virtual WorkStationsGroup WorkStationsGroup { get; set; }
    }
}
