//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpyWcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagesForGroup
    {
        public int PagesForGroupId { get; set; }
        public Nullable<int> AcceptablePagesGroupId { get; set; }
        public Nullable<int> AcceptablePageId { get; set; }
    
        public virtual AcceptablePage AcceptablePage { get; set; }
        public virtual AcceptablePagesGroup AcceptablePagesGroup { get; set; }
    }
}
